## Tipos de Variables
```
* Variables Primitivas
    * String    " ", ' '
    * Integer   23
    * Booleanos True, False
    * Complejos  234j
    * Flotantes  3.14
* Variables Colectoras
    * Mutables
        * Listas
            Arreglos:
                Vectores
                    Vectores Filas [2, 3 4, 5, 6, 7]
                    Vectores Columnas [[3], [2], [4], [5]]
        * Matrices
            [
                [
                    [], [], []
                ], 
                [
                    [], [], []
                ], 
            
            ]
        * Diccionarios
            {key: valor}
    * Inmutables
        * Tuplas ()
        * Conjuntos {12, 234, Jean Charly,}
```

# Palabras Reservadas

In [3]:
import keyword

keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [21]:
#Variables Primitivas

nombre = "Jean Charly"
apellidos = 'Joseph'
print(nombre, apellidos)


#Concatenar

print("Forma 1")
nombreCompleto = nombre + " " + apellidos
print(nombreCompleto)

print("Forma 2")
nombreCompleto1 = "%s %s %s"%(apellidos, apellidos, apellidos)
print(nombreCompleto1)

print("Forma 3")
nombreCompleto2 = '{} {}'.format(nombre, apellidos)
print(nombreCompleto2)

print("Forma 4")
nombreCompleto3 = f"{nombre} {apellidos}"
print(nombreCompleto3)

Jean Charly Joseph
Forma 1
Jean Charly Joseph
Forma 2
Joseph Joseph Joseph
Forma 3
Jean Charly Joseph
Forma 4
Jean Charly Joseph


In [26]:
solicitudNombre = int(input("Ingrese su numero: "))

print(solicitudNombre)
print(type(solicitudNombre))

23423
<class 'int'>


In [28]:
print(str(solicitudNombre) + nombreCompleto)

23423Jean Charly Joseph


In [29]:
#Numericos

a = 50     #Entero
b = 3.14   #Float
c = 4j     #Complex

In [34]:
#Operaciones

print("Suma\n")
print(a + c)
print(a + a)
print(a + b)

print("Resta\n")
print(a - c)
print(a - a)
print(a - b)


print("Multiplicar\n")
print((a + c) * 2)
print(a + a)
print(a + b)

Suma

(50+4j)
100
53.14
Resta

(50-4j)
0
46.86
Multiplicar

(100+8j)
100
53.14


# Estructuras Colectoras

### Listas


```
                -5          -4    -3  -2        -1
elementos = ['JEAN CHARLY', 24, True, 3j, ["Nikola Tesla']]
                0           1     2   3        4
elementos[INDICE]
```


In [3]:
#Listas
elementos = ["Jean Charly", 23, True, 4j, 3.14, ['Nikola', "Tesla", 32]]


In [6]:
#Tamañ0

nombre = "Jean Charly"
print(len(nombre))

print("Listas")
print(elementos, "<<>>", len(elementos))

11
Listas
['Jean Charly', 23, True, 4j, 3.14, ['Nikola', 'Tesla', 32]] <<>> 6


### Indice
#### elemento[$\real$]

In [9]:
print(elementos[-6])

Jean Charly


In [13]:
print(elementos[5][-1])

32


In [15]:
print(type(elementos))

<class 'list'>


### Slice


In [95]:
#Parte 1

elementos1 = elementos[0:3]
print(elementos1)

elemento4 = ['Marie Curie', 4j, True,"Nikola", "Tesla", 'Jean Charly']
print(elemento4)

['Jean Charly', 23, True]
['Marie Curie', 4j, True, 'Nikola', 'Tesla', 'Jean Charly']


In [99]:
#Parte 2
elemento4[1:]

[4j, True, 'Nikola', 'Tesla', 'Jean Charly']

In [100]:
#Parte 3
elemento4[:4]

['Marie Curie', 4j, True, 'Nikola']

In [116]:
#Parte 4
elemento4[:]

['Marie Curie', 4j, True, 'Nikola', 'Tesla', 'Jean Charly']

In [114]:
#Parte 4
elemento4[0:5:3]

['Marie Curie', 'Nikola']

In [19]:
elementos + elementos1

['Jean Charly',
 23,
 True,
 4j,
 3.14,
 ['Nikola', 'Tesla', 32],
 'Jean Charly',
 23,
 True]

In [20]:
elementos * 3

['Jean Charly',
 23,
 True,
 4j,
 3.14,
 ['Nikola', 'Tesla', 32],
 'Jean Charly',
 23,
 True,
 4j,
 3.14,
 ['Nikola', 'Tesla', 32],
 'Jean Charly',
 23,
 True,
 4j,
 3.14,
 ['Nikola', 'Tesla', 32]]

In [23]:
elementos += elementos

In [24]:
elementos

['Jean Charly',
 23,
 True,
 4j,
 3.14,
 ['Nikola', 'Tesla', 32],
 'Jean Charly',
 23,
 True,
 4j,
 3.14,
 ['Nikola', 'Tesla', 32]]

In [56]:
elementos2 = []
print(elementos2)


[]


In [57]:
#Append

elementos2.append("Marie Curie")
print(elementos2)

['Marie Curie']


In [58]:
elementos3 = elementos2


In [83]:
print("Elementos3: ", id(elementos3), "\n" "Elementos2 :", id(elementos2),  "\n" "Elementos4 :", id(elementos4))

Elementos3:  124242400999488 
Elementos2 : 124242400999488 
Elementos4 : 124242399063872


In [67]:
elementos3.append(34)
print(elementos2)
print(elementos3)

['Marie Curie', 34, 34, 34, 34, 34]
['Marie Curie', 34, 34, 34, 34, 34]


In [70]:
elementos4 = elementos3.copy()
print(elementos2)
print(elementos3)
print(elementos4)

['Marie Curie', 34, 34, 34, 34, 34]
['Marie Curie', 34, 34, 34, 34, 34]
['Marie Curie', 34, 34, 34, 34, 34]


In [71]:
elementos4.append("Jean Charly")
print(elementos2)
print(elementos3)
print(elementos4)

['Marie Curie', 34, 34, 34, 34, 34]
['Marie Curie', 34, 34, 34, 34, 34]
['Marie Curie', 34, 34, 34, 34, 34, 'Jean Charly']


In [80]:
elementos2.pop()
print(elementos2)
print(elementos3)

[]
[]


### Iterar

# $$\sum^{n}_{i=1} x_i$$

```
PARA i EN EL RANGO(n){
    IMPRIMI(x_i)
}
```

In [118]:
for i in range(len(elemento4)):
    print(i, elemento4[i])

0 Marie Curie
1 4j
2 True
3 Nikola
4 Tesla
5 Jean Charly


In [120]:
for i in elemento4:
    print(i)

Marie Curie
4j
True
Nikola
Tesla
Jean Charly


In [126]:
nuevaLista = []
for i in range(len(elemento4)):
    if elemento4[i] not in ["Marie Curie", 'Jean Charly', 4j, "Tesla"]:
        print(elemento4[i])
        nuevaLista.append(elemento4[i])
print(nuevaLista)
print(elemento4)

True
Nikola
[True, 'Nikola']
['Marie Curie', 4j, True, 'Nikola', 'Tesla', 'Jean Charly']


In [12]:
import numpy as np


a1 = np.array([2, 3, 4, 5, 34.4], dtype=int)
a1

#Complejo > [Entero, Flotante]
#Flotante > [Entero]
#String > [Entero, Flotante, Complejo]

array([ 2,  3,  4,  5, 34])

In [21]:
elemento1 = []

for i in range(1, 10):
    elemento1.append(i)
print(elemento1)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [25]:
[i if i == 5 else "Hola" for i in range(1, 10)]

['Hola', 'Hola', 'Hola', 'Hola', 5, 'Hola', 'Hola', 'Hola', 'Hola']

In [20]:
db1 = set(['nombre', 'apellidos', 'edad', 'telefono'])
 
db2 = set(['nombre', 'apellidos', 'edad','sex', 'altura'])
db2

#Diferencia

db2 - db1

db2.intersection(db1)

#Union

db2 | db1

{'altura', 'apellidos', 'edad', 'nombre', 'sex', 'telefono'}

In [36]:
fila = [2, 3, 4, 5, 5]
columnas = [['a'], ['b'],['c']]
matrices = []
for i in range(len(fila)):
    for j in range(len(columnas)):
        matrices.append([fila[i],columnas[j]])
matrices

[[2, ['a']],
 [2, ['b']],
 [2, ['c']],
 [3, ['a']],
 [3, ['b']],
 [3, ['c']],
 [4, ['a']],
 [4, ['b']],
 [4, ['c']],
 [5, ['a']],
 [5, ['b']],
 [5, ['c']],
 [5, ['a']],
 [5, ['b']],
 [5, ['c']]]

In [38]:
escalar = 5

v1 = np.array([3, 4, 5, 6])
v1 * escalar

array([15, 20, 25, 30])

In [45]:
vv = [3, 4, 5, 6]
escalar1  = 5
# vv1 = []

# for i in range(len(vv)):
#     vv1.append(vv[i] * escalar1)
# # vv1

[vv[i] * escalar1 for i in range(len(vv))]


[15, 20, 25, 30]

In [48]:
def prueba(x):
    return x ** 2

np.vectorize(prueba)(v1)

array([ 9, 16, 25, 36])

# Control de Flujos

    * Anidado
    * Cascada

```
SI (CONDICION) ENTONCES{
    SENTENCIA (VERDADERO)
}
SINO{
    SENTENCIA (FALSO)
}
```

# Operadores de Comparación
### Son factores Booleanos

```
== Igual
< Menor
> Mayor
>= Mayor Igual
<=  Menor Igual
!=, <> Diferencia
```


In [1]:
#Enunciado (Simple y Compuesto)
## Simple

(5 > 10)


False

In [2]:
if (5 > 10):
    print("Saludo")
else:
    print("Lo siento mucho")

Lo siento mucho


## Conectores | Operadores Logicos
```
Y (and &&) -> V; VV
O (or  ||) -> V; VF
No (not ) -> F; V - V; F
```

In [3]:
#Compuestas

#   V             V
(10 <= 10) and (20 != 10)
#out V


True

In [4]:
#
#   V             F
(10 <= 10) or (24 == 10)
#out V

True

In [6]:
#   V             F
(10 <= 10) or not (20 != 10)
#out V

True

In [7]:
if (10 <= 10) and (20 != 10):
    print("Excelente")
else:
    print("Lo siento")

Excelente


In [10]:
#Aninado
nombre = "Jean Charly"
datos = input("Ingrese su nombre: ")
if not(10 <= 10) and (20 != 10):
    if nombre == datos:
        print("Benvenido seas", datos)
    else:
        print("Nombre o datos invalido")
else:
    print("Lo siento mucho")

Lo siento mucho


In [19]:
statusCode = 403

if statusCode == 200 or statusCode == 201 or statusCode == 204:
    print("Conexion ok")
elif statusCode == 404:
    print("Pagina no encontrada")
elif statusCode == 504:
    print("Servidor no encontrado")
else:
    print("Usted no tiene internet")


Conexion ok


In [17]:
statusCode = int(input("Ingrese estatus HTTPS: "))
match statusCode:
    case 200 | 201 | :
        print("Conexion ok o un push")
    case 404:
        print("Pagina no encontrada")
    case 504:
        print("Servidor no encontrado")
    case _:
        print("Usted no tiene internet")

Conexion ok o un push
