# Variables
```
Estructuras Primitivas
- String '', ""
- Integer $\mathbb{R}$
- Boolen [Verdadero - Falso]
- Complejo [$\mathbb{R}$ j]
- Float - $\pi$

- Lenguaje No tipado

<tipo> <nombreVariable> = <valorVariable>

- lenguaje tipado

<nombreVariable> = <valorVariable>
``````

In [17]:
nombre = "Jean Charly"
#string nombre = valor
print(nombre)

edad = 23
pi = 3.14
sexo = False
comple = 43j

Jean Charly


# Variables Estructuradas

- Mutables
    
    ''' Son todas aquellas que se puede modificar despues de haber sido creadas
        llamandolo por su indice'''

    * Listas -> []
        - Listas
            """Es una lista cuando existen diferentes elementos que no son del mismo tipo"""
        - Arreglos
            """Es un arreglo cuando el tipo de datos corresponde todo a lo mismo"""
        - Matrices
                """Es una matriz cuando exite N cantidad de Arreglos con valores de mismo tipo"""
    * Diccionarios -> {<keys>: <valor>}
    
- Inmutables
'''No se puede modificar despues de haber sido creadas'''
    * Tuplas -> ( )
    * Conjuntos -> { }

## Listas

In [43]:
elementos = ["Jean Charly", "Joseph", 32, False]
elementos

['Jean Charly', 'Joseph', 32, False]

In [44]:
elementos.append("Leer")
elementos

['Jean Charly', 'Joseph', 32, False, 'Leer']

### Indices

```
 -5                 -4    -3    -2        -1
['Jean Charly', 'Joseph', 32, False, 'Leer']
        0           1      2   3        4
```

In [29]:
elementos[0] = "Jose Tesla"
elementos

['Jose Tesla', 'Joseph', 32, False, 'Leer']

In [31]:
elementos[0:3]

['Jose Tesla', 'Joseph', 32]

In [45]:
buffer = []
numIndice = int(input("Ingrese el valor que desea borrar: "))
buffer.append(elementos[numIndice])
elementos.pop(numIndice)
elementos

['Joseph', 32, False, 'Leer']

In [46]:
buffer

['Jean Charly']

In [47]:
elementos.insert(0, buffer[0])
elementos

['Jean Charly', 'Joseph', 32, False, 'Leer']

In [48]:
elementos[0] = "Charly"
elementos

['Charly', 'Joseph', 32, False, 'Leer']

# Tupla

In [51]:
elementoTuplas = ("Jean Charly", "Joseph", 32, False)
elementoTuplas

('Jean Charly', 'Joseph', 32, False)

In [53]:
elementoTuplas[0] = "Charly"

TypeError: 'tuple' object does not support item assignment

# Diccionarios
```
{<keys>: <valor>}
```


In [56]:
elementosDicc = {"nombre": "Jean Charly", "apellidos": "Joseph", "edad": 32, "sexo": False}
elementosDicc

{'nombre': 'Jean Charly', 'apellidos': 'Joseph', 'edad': 32, 'sexo': False}

In [59]:
elementosDicc['nombre'] = "Nikola"
elementosDicc

{'nombre': 'Nikola', 'apellidos': 'Joseph', 'edad': 32, 'sexo': False}

In [73]:
elementosDiccM = {'nombres': ["Jean Charly", "Nikola", "Marie"], "apellidos": ["Joseph", "Tesla", "Curie"], "edad": [32, 18, 22], "sexo": [False, False, True]}
elementosDiccM

{'nombres': ['Jean Charly', 'Nikola', 'Marie'],
 'apellidos': ['Joseph', 'Tesla', 'Curie'],
 'edad': [32, 18, 22],
 'sexo': [False, False, True]}

In [61]:
import polars as pl

pl.DataFrame(elementosDiccM)

shape: (3, 4)
┌─────────────┬───────────┬──────┬───────┐
│ nombres     ┆ apellidos ┆ edad ┆ sexo  │
│ ---         ┆ ---       ┆ ---  ┆ ---   │
│ str         ┆ str       ┆ i64  ┆ bool  │
╞═════════════╪═══════════╪══════╪═══════╡
│ Jean Charly ┆ Joseph    ┆ 32   ┆ false │
│ Nikola      ┆ Tesla     ┆ 18   ┆ false │
│ Marie       ┆ Curie     ┆ 22   ┆ true  │
└─────────────┴───────────┴──────┴───────┘

In [64]:
elementosDiccM['nombres'][0] = "Frederic"

In [68]:
elementosDiccM['nombres'][0:2] = "Jean Charly"

In [75]:
for i in range(len(elementosDiccM["sexo"])):
    if elementosDiccM["sexo"][i] == False:
        elementosDiccM["sexo"][i] = True
    else:
        elementosDiccM["sexo"][i] = True

elementosDiccM["sexo"]

[True, True, True]

In [77]:
import numpy as np

In [80]:
elemento2 = np.array(elementosDiccM["sexo"])

In [82]:
np.vectorize(lambda x: False if x == True else False)(elemento2)

array([False, False, False])

In [83]:
arreglo1 = [3, 3, 4, 5, 6, 7, 29]
arreglo1 * 2

[3, 3, 4, 5, 6, 7, 29, 3, 3, 4, 5, 6, 7, 29]

In [84]:
[arreglo1[i] * 2 for i in range(len(arreglo1))]

[6, 6, 8, 10, 12, 14, 58]

In [85]:
nuevoArreglo = []
for i in range(len(arreglo1)):
    nuevoArreglo.append(arreglo1[i] * 2 )
nuevoArreglo

[6, 6, 8, 10, 12, 14, 58]

In [86]:
np.array(arreglo1) * 2

array([ 6,  6,  8, 10, 12, 14, 58])

# Conjuntos

In [89]:
conjunto1 = {2, 3, 3, 4, 455, 4, 3, }
conjunto1

conjunto2 = {2, 3, 33, 4, 5, 6}
conjunto2

{2, 3, 4, 5, 6, 33}

In [91]:
conjunto2 - conjunto1

{5, 6, 33}

In [93]:
conjunto2.intersection(conjunto1)

{2, 3, 4}

In [12]:
from random import randint
import math
import numpy as np


elementos = [randint(1, 100) for i in range(10)]
elementos

[97, 83, 17, 99, 79, 63, 73, 30, 83, 82]

In [19]:
def prueba(x):
    valor = np.array(elementos) * x
    return valor
prueba(5)
            

array([485, 415,  85, 495, 395, 315, 365, 150, 415, 410])

In [15]:
elemento4 = lambda x: np.array(elementos) * x

In [18]:
elemento4(6)

array([582, 498, 102, 594, 474, 378, 438, 180, 498, 492])

In [20]:
import pandas as pd

dataset = {
        "Nombre": ["Elemento_%s"%randint(1,100) for i in range(20)],
        "Apellido": ["Elemento_%s"%randint(1,100) for i in range(20)],
        "Sexo": [randint(0, 1) for i in range(20)]
}
df = pd.DataFrame(dataset)
df

Nombre     Apellido  Sexo
0    Elemento_22  Elemento_86     1
1     Elemento_5  Elemento_62     0
2    Elemento_67  Elemento_17     1
3    Elemento_79  Elemento_90     0
4    Elemento_99  Elemento_92     0
5    Elemento_65  Elemento_62     1
6   Elemento_100  Elemento_69     1
7    Elemento_91  Elemento_56     1
8    Elemento_60  Elemento_49     1
9    Elemento_88  Elemento_56     1
10   Elemento_46  Elemento_48     0
11   Elemento_18   Elemento_8     0
12   Elemento_12  Elemento_32     1
13    Elemento_7  Elemento_57     1
14   Elemento_78   Elemento_5     1
15   Elemento_33  Elemento_22     1
16   Elemento_10  Elemento_30     0
17    Elemento_3  Elemento_99     0
18   Elemento_33  Elemento_95     0
19    Elemento_6  Elemento_62     1

In [23]:
def cambioSexo(x):
    if x == 1:
        return "Femenino"
    else:
        return "Masculino"

In [24]:
df["Sexo Cualif"] = df['Sexo'].apply(lambda x: "Feminino" if x == 1 else "Masculino")
df["Sexo Funcion"] = df['Sexo'].apply(cambioSexo)

In [25]:
df

Nombre     Apellido  Sexo Sexo Cualif Sexo Funcion
0    Elemento_22  Elemento_86     1    Feminino     Femenino
1     Elemento_5  Elemento_62     0   Masculino    Masculino
2    Elemento_67  Elemento_17     1    Feminino     Femenino
3    Elemento_79  Elemento_90     0   Masculino    Masculino
4    Elemento_99  Elemento_92     0   Masculino    Masculino
5    Elemento_65  Elemento_62     1    Feminino     Femenino
6   Elemento_100  Elemento_69     1    Feminino     Femenino
7    Elemento_91  Elemento_56     1    Feminino     Femenino
8    Elemento_60  Elemento_49     1    Feminino     Femenino
9    Elemento_88  Elemento_56     1    Feminino     Femenino
10   Elemento_46  Elemento_48     0   Masculino    Masculino
11   Elemento_18   Elemento_8     0   Masculino    Masculino
12   Elemento_12  Elemento_32     1    Feminino     Femenino
13    Elemento_7  Elemento_57     1    Feminino     Femenino
14   Elemento_78   Elemento_5     1    Feminino     Femenino
15   Elemento_33  Elemento_22     1    Feminino     Femenino
16   Elemento_10  Elemento_30     0   Masculino    Masculino
17    Elemento_3  Elemento_99     0   Masculino    Masculino
18   Elemento_33  Elemento_95     0   Masculino    Masculino
19    Elemento_6  Elemento_62     1    Feminino     Femenino

In [28]:
df['Sexo Vectorizado'] = np.vectorize(lambda x: "Feminino" if x == 1 else "Masculino")(df['Sexo'].to_numpy())

In [29]:
df

Nombre     Apellido  Sexo Sexo Cualif Sexo Funcion Sexo Vectorizado
0    Elemento_22  Elemento_86     1    Feminino     Femenino         Feminino
1     Elemento_5  Elemento_62     0   Masculino    Masculino        Masculino
2    Elemento_67  Elemento_17     1    Feminino     Femenino         Feminino
3    Elemento_79  Elemento_90     0   Masculino    Masculino        Masculino
4    Elemento_99  Elemento_92     0   Masculino    Masculino        Masculino
5    Elemento_65  Elemento_62     1    Feminino     Femenino         Feminino
6   Elemento_100  Elemento_69     1    Feminino     Femenino         Feminino
7    Elemento_91  Elemento_56     1    Feminino     Femenino         Feminino
8    Elemento_60  Elemento_49     1    Feminino     Femenino         Feminino
9    Elemento_88  Elemento_56     1    Feminino     Femenino         Feminino
10   Elemento_46  Elemento_48     0   Masculino    Masculino        Masculino
11   Elemento_18   Elemento_8     0   Masculino    Masculino        Masculino
12   Elemento_12  Elemento_32     1    Feminino     Femenino         Feminino
13    Elemento_7  Elemento_57     1    Feminino     Femenino         Feminino
14   Elemento_78   Elemento_5     1    Feminino     Femenino         Feminino
15   Elemento_33  Elemento_22     1    Feminino     Femenino         Feminino
16   Elemento_10  Elemento_30     0   Masculino    Masculino        Masculino
17    Elemento_3  Elemento_99     0   Masculino    Masculino        Masculino
18   Elemento_33  Elemento_95     0   Masculino    Masculino        Masculino
19    Elemento_6  Elemento_62     1    Feminino     Femenino         Feminino

# Clases

In [35]:
class Perfil:
    def __init__(self, nombre, apellido, sexo, edad, altura):
        self.nombre = nombre
        self.apellido = apellido
        self.sexo = sexo
        self.edad = edad 
        self.altura = altura
        self.estado = None

    def __repr__(self):
        return "Bienvenido %s %s"%(self.nombre, self.apellido)
    
    def cambioEstado(self, est):
        self.estado = est
        return self.estado
    




In [38]:
p1 = Perfil("Jean Charly", "Joseph", False, 32, 1.3)
p1.__repr__()
p1.cambioEstado("")


''

# Crear DataFrame

In [45]:
columnas = ["Nombres", "Apellidos", "Sexo", "Edad", "Altura", "Estado"]
dataset = {columnas[i]: [] for i in range(len(columnas))}
dataset

{'Nombres': [],
 'Apellidos': [],
 'Sexo': [],
 'Edad': [],
 'Altura': [],
 'Estado': []}

In [50]:

nombre = input("Ingrese su nombre: ")
apellidos = input("Ingrese su apelidos: ")
sexo = bool(input("Ingrese su sexo  [F=True, M=False]: "))
edad = int(input("Ingrese su edad : "))
altura = float(input("Ingrese su altura: "))

perfil = Perfil(nombre, apellidos, sexo, edad, altura)
perfil.__repr__()
# estado = input("En que estado se cuentra actualmente: ")
# perfil.cambioEstado(estado)


#Registro al dataset

dataset['Nombres'].append(perfil.nombre)
dataset['Apellidos'].append(perfil.apellido)
dataset['Sexo'].append(perfil.sexo)
dataset['Edad'].append(perfil.edad)
dataset['Altura'].append(perfil.altura)
# dataset['estado'].append(perfil.estado)

dataset

{'Nombres': ['Jean Charly', 'Jean Charly', 'Nikola', 'Marie'],
 'Apellidos': ['Joseph', 'Joseph', 'Tesla', 'Curie'],
 'Sexo': [True, True, True, True],
 'Edad': [32, 32, 43, 20],
 'Altura': [1.4, 1.4, 2.1, 1.2],
 'Estado': []}

In [57]:
df = pd.DataFrame(dataset)
df

Nombres Apellidos  Sexo  Edad  Altura Estado
0  Jean Charly    Joseph  True    32     1.4   None
1  Jean Charly    Joseph  True    32     1.4   None
2       Nikola     Tesla  True    43     2.1   None
3        Marie     Curie  True    20     1.2   None

# Ficheros - Escritura de Archivo

```
    OPEN <NOMBRE>.[CSV, XLSX, TXT, DOCS], [PERMISO <r, w, a, x>], encoding='UTF-8' 
```


In [1]:
EXTENSIONES = ['xlsx', 'csv', 'txt', 'docs', 'sql']

for i in range(len(EXTENSIONES)):
    with open("PruebaArchivos/Elemento.%s"%EXTENSIONES[i], 'w', encoding='UTF-8') as f:
        f.close()

In [2]:
with open("PruebaArchivos/Elemento.csv", 'w', encoding='UTF-8') as f:
    f.writelines("Esto es una prueba... jejejejejej")
    f.close()

In [56]:
import os

if os.path.exists("PruebaArchivos/Elemento.csv"):
    print("Este documento ya existe.....")
else:
    with open("PruebaArchivos/Elemento.csv", 'w', encoding='UTF-8') as f:
        f.writelines("Bienvenido, estudiantes del ITLA")
        f.close()

Este documento ya existe.....


In [55]:
with open("PruebaArchivos/Elemento.csv", 'a', encoding='UTF-8') as f:
    f.writelines("\nEsto es una prueba... jejejejejej")
    
    f.close()

In [60]:
#Modelo
class Estudiante:
    def __init__(self, nombre, apellido, edad):
        self.nombre = nombre
        self.apellido = apellido
        self.edad = edad
    def __str__(self):
        return "Bienvenido %s"%self.nombre
    

In [63]:
#"Vista"
def registro():
    nombre = input("Ingrese su nombre: ")
    apellido = input("Ingrese su apellidos: ")
    edad = int(input("Ingrese su edad: "))
    return nombre, apellido, edad


In [67]:
#Controlador
reg = registro()
estudianteInstancia = Estudiante(reg[0], reg[1], reg[2])
with open("RegistroEstudiantes.csv", 'a', encoding='UTF-8') as f:
    f.writelines("%s |%s| %s\n"%(estudianteInstancia.nombre, estudianteInstancia.apellido, estudianteInstancia.edad))
    f.close()

In [57]:
if os.path.exists("RegistroEstudiantes.csv"):
    print("Este archivo, ya existe.")
else:
    with open("RegistroEstudiantes.csv", 'a', encoding='UTF-8') as f:
        f.writelines("Nombre |Apellidos| edad\n")
        f.close()


In [66]:
#Registrar datos

with open("RegistroEstudiantes.csv", 'a', encoding='UTF-8') as f:
    f.writelines("%s |%s| %s\n"%(estudianteInstancia.nombre, estudianteInstancia.apellido, estudianteInstancia.edad))
    f.close()